name: "CI"

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build with Maven
      run: "mvn '-Dmaven.test.skip=true' clean package --file pom.xml"

    - name: Build test classes with Maven
      run: "mvn test-compile --file pom.xml"
