name: 'MTLX-C365 Automation Test'
on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

jobs:
  run_tests:
    runs-on: mx-self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
         maven-version: 3.6.1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '105.0.5195.52'
      - run: |
           chromedriver --url-base=/wd/hub &
      
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Generate Allure Report
        run: |
          mvn allure:report
      
      - name: Upload Allure Reports  
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-report
          path: ./target/allure-report

  Publish_test_reports:
   runs-on: mx-self-hosted
   needs: run_tests
   if: always()
   steps:
      - name: Create Directory
        run:  mkdir -p C:\inetpub\wwwroot\cx-allure-reports-web\C365\${{ github.run_number }}
      
      - name:  Downnload Allure Reports
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: C:\inetpub\wwwroot\cx-allure-reports-web\C365\${{ github.run_number }}

      - name: Send notification  
        run: |
          $body =@"
          Metrolinx C365 Automation Test  <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">run</a>  is completed <br>
          Related Allure report: <a href="http://10.194.108.90/C365/${{ github.run_number }}"> ${{ github.run_number }}</a> <br>
          "@
          Send-MailMessage -from 'noreply@metrolinx.com' -To 'prashant.ranjan2@wipro.com'-Subject 'C365 Regression Results' -Body $body -BodyAsHtml -SmtpServer 'smtp.gotransit.local'
